[package]
name = "clouds"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.35.2"
vulkano-win = "0.34.0"
vulkano-macros = "0.35.0"
winit = "0.30"
vulkano-shaders = "0.35.0"
glam="0.28.0"
game-loop = { version = "*", features = ["winit"] }
image = "0.25.9"
thiserror = "2.0.18"